### ISSUE TITLE
my vitacheat just wont show up.

### ISSUE THREAD

**Issue by CovanRei** [r0ah/vitacheat#34] opened 2018-10-30 22:52 UTC
**Note**:
Read the [Troubleshooting](https://github.com/r0ah/vitacheat/wiki/Troubleshooting) page before reporting any issues.

Yes, I read this.

**Describe the issue**
after following the installation instruction, I have all the files at right place, I even have my vitashell screen capture let others verified my works. for some reason, this vitacheat just wont pop out in any of my games.

I don't know if this is a proper channel to ask for help, but any suggestion or assistant will be greatly appreciate. 

**Please complete the following information:**
 - **Your PSVita Firmware version**: 3.65Enso/h-encore,
 - **ID**: PCSExxxxx, not just single game, all my games, but I’m install this for PCSH-10001.
 - **Version**: 1.00
 - **Type**: NoNpDrm,

thanks again :)

**Comment by RikuNoctis** [comment] 2018-10-30 23:05
Did you verify that the vitacheat plugin is listed on your config.txt like this?
```
*KERNEL
ur0:vitacheat/vitacheat.skprx
```
Also, do remember that you need to have the 2 plugins on your vita on 2 different locations.
```
vitacheat.skprx to ur0:vitacheat/
vitacheat.suprx to ux0:vitacheat/
```
As you can see, the .skprx goes into ur0:, while the .suprx goes into ux0: for it to work. You may need to create the folders named "vitacheat" first on those locations, then just copy over the plugins there. After that, you can open the vitacheat menu in-game using L + Right (D-Pad) (you can also use L + Left (D-Pad) to close it).

**Comment by CovanRei** [comment] 2018-10-30 23:09
@Riku

Yes, I have screen capture of those from vitashell and ask other verified, I put those files at correct spot.

I tried those combo, and I see no menu showed up.

**Comment by CovanRei** [comment] 2018-10-30 23:18
https://images.plurk.com/7nEVfuvzFGterGJN2Jot8K.jpg

https://images.plurk.com/1qvKCFM35T0xI2yCNEO0Ze.jpg

 https://images.plurk.com/5lkmxKnZapdKTR9apHYElj.jpg

**Comment by RikuNoctis** [comment] 2018-10-30 23:39
Check your config.txt like I first mentioned. You have the plugin listed under "ALL", which is for specific user applications instead of "KERNEL" which vitacheat requires.

**Comment by CovanRei** [comment] 2018-10-30 23:46
@RikuNoctis,

on the top of the screen capture, before *main, those are the lines for "Kernel" section.

I also heard some said don't but that last line under *all, some said yes, and I've tried both ways, and none of them works .....

**Comment by RikuNoctis** [comment] 2018-10-31 00:04
Remove the line below "ALL". You should only have one of them listed, which should be vitacheat.skprx.

**Comment by CovanRei** [comment] 2018-10-31 00:09
@RikuNoctis

yap, I've tried that already, its still not working .... sigh.

additional info, I thought VSH was in the way, and I'm not really need that, so I removed the VSH, but its not helping too.

**Comment by r0ah** [comment] 2018-11-02 18:18
Try re-copying the suprx and skprx files. I've encountered similar problem when transferring repatch with vitashell. The plugin is in KB but sometimes it (transfer) just fails. Also, try moving it up, maybe it has incompatibility issue with the kuio plugin.

**Comment by RikuNoctis** [comment] 2018-11-02 21:14
Like @r0ah said, try to move down your kuio plugin, or even better, disable it completely to check if there is any compatibility issues with kuio as that plugins can do some other things via kernel that vitacheat may need/modify.

**Comment by CovanRei** [comment] 2018-11-02 21:47
@r0ah @RikuNoctis  thank you for the reply, actually I somehow fixed the problem 2 days ago.

the reason I need the plug in , is for the game PCSH10004

so I found somebody write the config.txt in the way for plug in only work certain game (at least that's what I thought I see...)

anyway, in the config.txt right after the *main section and before the *NPXS10015
I added 
*PCSH10004
ux0:vitacheat/vitacheat.suprx

for some reason, it works now ....... and funny thing is , not just work for this game, all the game suddenly have the pop menu showed up after the combo keys.

I apologize didnt update here after my discover, but thank you for answering my question :)

Covan

**Comment by RikuNoctis** [comment] 2018-11-02 22:07
Well, yes, that's how you run specific plugins for specific apps with Henkaku, though the weird thing is that vitacheat works outside the specified ID as you said.

Well, at least the problem is solved (more or less) and you can now use vitacheat on your games. :)

**Comment by eighthdayregret** [comment] 2018-11-04 02:19
Closing this, as user has confirmed issue has been satisfactorily resolved.

**Closed by eighthdayregret** 2018-11-04 02:19 UTC
Labels: help

**Comment by hacker20182019** [comment] 2023-01-20 20:18
I realize this response is horrifically late but hopefully this could help someone else who might be searching for this issue. Vitacheat failing to launch (i.e. nothing happens) generally means you are using the incorrect plugin for your firmware.

I would also like to touch on some additional details (from my experience and what has worked for me) even though the OP did not inquire about them, again, in hopes that it may help someone else in the future. Contrary to a lot of advice and instructions floating out there, placing the vitacheat.skprx plugin in ur0 is not mandatory even when using SD2VITA. I am using SD2VITA but it's configured as my ux0 using autoplugin, and hence I am able to successfully use vitacheat in my ux0 without touching ur0. I simply placed both the vitacheat.skprx and vitacheat.suprx in the vitacheat folder in my ux0 (along with the font, db....etc folders) and in my config.txt file (which is located in ux0:tai) i added the line:
*KERNEL 
ux0:vitacheat\vitacheat.skprx
Profit!
Troubleshooting:
As mentioned if you can't launch vitacheat by pressing L1 and the right arrow then it most likely means you are not using the correct vitacheat version for your firmware. If on the other hand you CAN launch it and activate the [cheats](https://gbatemp.net/forums/cheat-codes-add-and-request.412/) and they turn blue but are ineffective (i.e. do nothing for you in game) then chances are you are using a region and/or dump method of the game that is not compatible with the [cheat codes](https://gbatemp.net/forums/cheat-codes-add-and-request.412/). The [cheat codes](https://gbatemp.net/forums/cheat-codes-add-and-request.412/) are usually specific to a certain region and/or dump method e.g Europe with a mai dump or China with a nonpdrm....etc, etc.

My setup:
PS Vita 1000 (slim) white
3.60 firmware with Ensō
SD2VITA configured as ux0
